version: '3'
services:
 server:
  build:
   context: .
   dockerfile: Dockerfile
  command: ["./TIN", "IPV4", "255.255.255.255", "3000", "1"]
 mobile:
  build:
   context: .
   dockerfile: Dockerfile
  command: ["./TIN", "IPV4", "255.255.255.255", "3000", "0"]
