version: '3'
services:
 server:
  build:
   context: .
   dockerfile: Dockerfile
  command: ["./TIN", "IPV6", "ff02::1", "3000", "1"]
 mobile:
  build:
   context: .
   dockerfile: Dockerfile
  command: ["./TIN", "IPV6", "ff02::1", "3000", "0"]
networks:
 default:
  external:
   name: mobile_nodes_network
